---
title: "git_00"
author: "Kelly Acevedo"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
"I have a fairy by my side
Which says I must not sleep,
When once in pain I loudly cried
It said "You must not weep"
If, full of mirth, I smile and grin,
It says "You must not laugh"
When once I wished to drink some gin
It said "You must not quaff".

When once a meal I wished to taste
It said "You must not bite"
When to the wars I went in haste
It said "You must not fight".

"What may I do?" at length I cried,
Tired of the painful task.
The fairy quietly replied,
And said "You must not ask".
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

"Some say the world will end in fire,
Some say in ice.
From what I’ve tasted of desire
I hold with those who favor fire.
But if it had to perish twice,
I think I know enough of hate
To say that for destruction ice
Is also great
And would suffice."

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,
      Shining with all his might:
He did his very best to make
      The billows smooth and bright —
And this was odd, because it was
      The middle of the night.

The moon was shining sulkily,
      Because she thought the sun
Had got no business to be there
      After the day was done —
"It's very rude of him," she said,
      "To come and spoil the fun."
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

"The rain is raining all around,
It falls on field and tree,
It rains on the umbrellas here,
And on the ships at sea."